name: Publish to Hashnode

on:
  push:
    branches:
      - main
    paths:
      - "_hashnode_posts/*.md"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Validate Hashnode post
        uses: Hashnode/publish-github-action@v1
        with:
          access-token: ${{ secrets.HASHNODE_PAT }}
          publication-host: blog.nextgreviews.com
          posts-directory: _hashnode_posts
          max-files: 10
          dry-run: false
